### ISSUE TITLE
Open-Source UNIX/MAC - "Failed to load indicator STC" & "The storable module was unable to store the child's data structure to the temp file"

### ISSUE THREAD

**Issue by bruno-berchielli** [xFFFFF/Gekko-BacktestTool#10]
Hello
Thank you so much for this tool! The potential is incredible... 

I've followed exactly the instructions below:

> Open Source: Other Unix-like OS
> 
> Clone git https://github.com/xFFFFF/Gekko-BacktestTool
> Copy files to Gekko's main directory
> Install dependies:
> $ su
> $ cpan install Parallel::ForkManager Time::ParseDate Time::Elapsed Getopt::Long List::MoreUtils File::chdir Statistics::Basic DBI DBD::SQLite JSON::XS TOML File::Basename File::Find::Wanted Template LWP::UserAgent LWP::Protocol::https Set::CrossProduct DBD::CSV Text::Table File::Copy

But I'm gettin the following errors : 
<img width="1105" alt="captura de tela 2018-04-29 as 01 18 11" src="https://user-images.githubusercontent.com/34753722/39401677-4707d006-4b4b-11e8-9e88-5da50bc14d6e.png">

<img width="1376" alt="captura de tela 2018-04-29 as 01 18 28" src="https://user-images.githubusercontent.com/34753722/39401676-46edf38e-4b4b-11e8-912e-bd54752ca4fc.png">

I've double checked and all the informed dependencies are installed and up-to-date, including perl. 

Thanks

**Comment by xFFFFF** [comment]
It appears because backtest ended in failure (did not return the variables expected by BacktestTool).

In other words: if you find the cause of the error "failed to load indicator" (this error comes from Gekko, not BacktestTool) then the above error will not appear. But that needs fixing, thanks for reporting.

To fix the error coming from the gekko check if you have the STC.js file in the gekko / strategies / indicators directory. If "yes" it is possible that you did not install the required module for node. Try the command `npm install mathjs`. The second required dependency is the MACD.js file in the indicators directory, which in turn requires EMA.js.

![Screen](http://i.imgur.com/r58RTel.png)

You can check the required dependencies for each indicator by opening the file in a text editor and looking for the phrase "require". If you have a problem with the load indicator, then you have to check all the required dependencies and sub-dependencies (required files).

**Comment by bruno-berchielli** [comment]
Hello @xFFFFF 

Thank you. All the requirements were already in place for the indicator but it's still failing (no errors when running Gekko UI).
Anyway, I asked about the indicator loading problem because the strategy in question do not require this indicator, so maybe BacktestTool is loading all the indicators anyway? Is this by design? 

About the second error, it generates the CSV file correctly anyway, so not much problem. Upon giving the machine a hard-reset, the error disappeared. Maybe the dependencies did not loaded correctly at first. 

Thank you for your attention. Please, close this Issue.

**Comment by xFFFFF** [comment]
> Anyway, I asked about the indicator loading problem because the strategy in question do not require this indicator, so maybe BacktestTool is loading all the indicators anyway? Is this by design?
BacktestTool use all available strategies as default.   

![s](http://i.imgur.com/MNVVU3d.png)
Above is default config. Value from line 5 mean "do backtest for all strategies available in gekko/strategies" folder. I added it together with other strategies as an example (I have to describe it better). So, by default BacktestTool performs backtest of all strategies, and then again performs backtest for MACD, CCI, RSI. Everything between brackets can be changed for other values. Line 12 mean "perform backtests for all available pairs from sqlite db", can You remove it too.

It's nice to hear that BacktestTool also works on Mac OS X
